name: Docker CI

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: "crffwebappdev"
  AZURE_CONTAINER_REGISTRY_URL: "crffwebappdev.azurecr.io"
  CONTAINER_NAME: "ffwebapp"
  RESOURCE_GROUP: "rg_aksgitopspush"


jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        run: az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY_URL }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: src/ffwebapp
          file: src/ffwebapp/Dockerfile
          tags: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          push: true