name: Docker CI

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: "crffwebappdev.azurecr.io"
  CONTAINER_NAME: "ffwebapp"
  RESOURCE_GROUP: "rg_aksgitopspush"


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/ffwebapp


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Builds and pushes an image up to your Azure Container Registry
      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} .